before_build:
  - nuget restore
  
deploy:
  release: myproduct-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: 45fa9084af6d1ee54ee58062292ec752610e67d9 # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only